package divytime
// Package divytime provides a simulated 3-tuple timestamp oracle.
//
// In production this would call a remote ordering service (e.g. a Divy
// broker).  Here we generate timestamps locally so that benchmarks and tests
// can simulate the full 3-tuple (EpochID, BrokerID, AssignedTs) without an
// external dependency.
//































































































































}	}		TotalNs: total,		MaxNs:   sorted[len(sorted)-1],		MinNs:   sorted[0],		P90Ns:   sorted[p90idx],		AvgNs:   total / int64(len(sorted)),		Count:   int64(len(sorted)),	return Stats{	}		p90idx = len(sorted) - 1	if p90idx >= len(sorted) {	p90idx := int(float64(len(sorted)) * 0.90)	}		total += v	for _, v := range sorted {	var total int64	}		sorted[j+1] = v		}			j--			sorted[j+1] = sorted[j]		for j >= 0 && sorted[j] > v {		j := i - 1		v := sorted[i]	for i := 1; i < len(sorted); i++ {	copy(sorted, s)	sorted := make([]int64, len(s))	// Simple insertion sort — sample windows are small (< 10 000).	}		return Stats{}	if len(s) == 0 {	o.mu.Unlock()	o.samples = o.samples[:0]	copy(s, o.samples)	s := make([]int64, len(o.samples))	o.mu.Lock()func (o *Oracle) Snapshot() Stats {// Snapshot returns a Stats snapshot and resets the internal sample buffer.}	TotalNs int64	MaxNs  int64	MinNs  int64	P90Ns  int64	AvgNs  int64	Count  int64type Stats struct {// Stats returns latency statistics over all recorded GetTimestamp calls.}	}, elapsed		AssignedTs: assigned,		BrokerID:   o.brokerID,		EpochID:    epochID,	return Timestamp{	o.mu.Unlock()	o.samples = append(o.samples, int64(elapsed))	o.mu.Lock()	elapsed := time.Since(start)	assigned := atomic.AddInt64(&o.counter, 1)	}		time.Sleep(o.simulatedDelay + jitter - o.simulatedDelay/10)		jitter := time.Duration(rand.Int63n(int64(o.simulatedDelay) / 5))		// Add jitter ±10 % so variability is visible in the p90.	if o.simulatedDelay > 0 {	start := time.Now()func (o *Oracle) GetTimestamp(epochID int64) (Timestamp, time.Duration) {// the call took (including any simulated delay).// GetTimestamp returns a Timestamp for the given epochID and records how long}	}		counter:        time.Now().UnixNano(),		simulatedDelay: simulatedDelay,		brokerID:       brokerID,	return &Oracle{func NewOracle(brokerID int64, simulatedDelay time.Duration) *Oracle {//     network/computation overhead.  Use 0 for no overhead.//   - simulatedDelay: extra sleep added to each GetTimestamp call to mimic//   - brokerID:       identifies this broker instance (1-based).//// NewOracle creates a new Oracle.}	samples []int64 // nanosecond durations of each GetTimestamp call	mu      sync.Mutex	simulatedDelay time.Duration	counter        int64 // atomic nanosecond counter for AssignedTs	brokerID       int64type Oracle struct {// Zero value is not usable; construct with NewOracle.//// Oracle generates 3-tuple timestamps and records per-call latency.}	AssignedTs int64	BrokerID   int64	EpochID    int64type Timestamp struct {// Timestamp is the 3-tuple used by the DuckDB storage layer.)	"time"	"sync/atomic"	"sync"	"math/rand"import (package divytime//	             Oracle instance, so two calls always produce distinct values.//	AssignedTs – monotonically increasing nanosecond counter within this//	             assigned the timestamp (use 1 for single-node setups).//	BrokerID   – fixed per Oracle instance; simulates the broker that//	             Preserves existing snapshot-read semantics.//	EpochID    – supplied by the caller (usually the Badger MVCC version).//// Timestamp semantics