// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CustomTs struct {
	_tab flatbuffers.Struct
}

func (rcv *CustomTs) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CustomTs) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *CustomTs) Epoch() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *CustomTs) MutateEpoch(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *CustomTs) Broker() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *CustomTs) MutateBroker(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *CustomTs) AssignedTs() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *CustomTs) MutateAssignedTs(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func CreateCustomTs(builder *flatbuffers.Builder, epoch uint32, broker uint32, assignedTs uint32) flatbuffers.UOffsetT {
	builder.Prep(4, 12)
	builder.PrependUint32(assignedTs)
	builder.PrependUint32(broker)
	builder.PrependUint32(epoch)
	return builder.Offset()
}
